name: "hugegraph-ci"

on:
  push:
    branches:
      - master
      - 'release-*'
      - 'test-*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      TRAVIS_DIR: hugegraph-server/hugegraph-dist/src/assembly/travis
      REPORT_DIR: target/site/jacoco
      BACKEND: ${{ matrix.BACKEND }}
      TRIGGER_BRANCH_NAME: ${{ github.ref_name }}
      HEAD_BRANCH_NAME: ${{ github.head_ref }}
      BASE_BRANCH_NAME: ${{ github.base_ref }}
      TARGET_BRANCH_NAME: ${{ github.base_ref != '' && github.base_ref || github.ref_name }}
      RELEASE_BRANCH: ${{ startsWith(github.ref_name, 'release-') || startsWith(github.ref_name, 'test-') || startsWith(github.base_ref, 'release-') }}

    strategy:
      fail-fast: false
      matrix:
        BACKEND: [ memory, cassandra, scylladb, hbase, rocksdb, mysql, postgresql ]
        JAVA_VERSION: [ '8', '11' ]

    steps:
      - name: Install JDK ${{ matrix.JAVA_VERSION }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.JAVA_VERSION }}
          distribution: 'zulu'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: mvn local path
        run: |
          which mvn

      - name: cat mvn
        run: |
          cat /usr/bin/mvn

      - name: cat /home/runner/.m2/settings.xml
        run: |
          cat /home/runner/.m2/settings.xml

      - name: remove setting.xml
        run: |
          rm -f $HOME/.m2/settings.xml
      - name: Add setting.xml
        run: |
          echo '<?xml version="1.0" encoding="UTF-8"?>

          <!--
          Licensed to the Apache Software Foundation (ASF) under one
          or more contributor license agreements.  See the NOTICE file
          distributed with this work for additional information
          regarding copyright ownership.  The ASF licenses this file
          to you under the Apache License, Version 2.0 (the
          "License"); you may not use this file except in compliance
          with the License.  You may obtain a copy of the License at
          
              http://www.apache.org/licenses/LICENSE-2.0
          
          Unless required by applicable law or agreed to in writing,
          software distributed under the License is distributed on an
          "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
          KIND, either express or implied.  See the License for the
          specific language governing permissions and limitations
          under the License.
          -->
          
          <!--
           | This is the configuration file for Maven. It can be specified at two levels:
           |
           |  1. User Level. This settings.xml file provides configuration for a single user,
           |                 and is normally provided in ${user.home}/.m2/settings.xml.
           |
           |                 NOTE: This location can be overridden with the CLI option:
           |
           |                 -s /path/to/user/settings.xml
           |
           |  2. Global Level. This settings.xml file provides configuration for all Maven
           |                 users on a machine (assuming they're all using the same Maven
           |                 installation). It's normally provided in
           |                 ${maven.conf}/settings.xml.
           |
           |                 NOTE: This location can be overridden with the CLI option:
           |
           |                 -gs /path/to/global/settings.xml
           |
           | The sections in this sample file are intended to give you a running start at
           | getting the most out of your Maven installation. Where appropriate, the default
           | values (values used when the setting is not specified) are provided.
           |
           |-->
          <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
            <!-- <! localRepository
             | The path to the local repository maven will use to store artifacts.
             |
             | Default: ${user.home}/.m2/repository
            <localRepository>/path/to/local/repo</localRepository> -->
          
          
            <localRepository>D:\apache-maven-3.6.1\mvn_resp</localRepository>
          
            <!-- interactiveMode
             | This will determine whether maven prompts you when it needs input. If set to false,
             | maven will use a sensible default value, perhaps based on some other setting, for
             | the parameter in question.
             |
             | Default: true
            <interactiveMode>true</interactiveMode>
            -->
          
            <!-- offline
             | Determines whether maven should attempt to connect to the network when executing a build.
             | This will have an effect on artifact downloads, artifact deployment, and others.
             |
             | Default: false
            <offline>false</offline>
            -->
          
            <!-- pluginGroups
             | This is a list of additional group identifiers that will be searched when resolving plugins by
            their prefix, i.e.
             | when invoking a command line like "mvn prefix:goal". Maven will automatically add the group
            identifiers
             | "org.apache.maven.plugins" and "org.codehaus.mojo" if these are not already contained in the
            list.
             |-->
            <pluginGroups>
              <!-- pluginGroup
               | Specifies a further group identifier to use for plugin lookup.
              <pluginGroup>com.your.plugins</pluginGroup>
              -->
          
              <pluginGroup>org.apache.tomcat.maven</pluginGroup>
              <pluginGroup>org.jacoco</pluginGroup>
          
            </pluginGroups>
          
            <!-- proxies
             | This is a list of proxies which can be used on this machine to connect to the network.
             | Unless otherwise specified (by system property or command-line switch), the first proxy
             | specification in this list marked as active will be used.
             |-->
            <proxies>
              <!-- proxy
               | Specification for one proxy, to be used in connecting to the network.
               |
              <proxy>
                <id>optional</id>
                <active>true</active>
                <protocol>http</protocol>
                <username>proxyuser</username>
                <password>proxypass</password>
                <host>proxy.host.net</host>
                <port>80</port>
                <nonProxyHosts>local.net|some.host.com</nonProxyHosts>
              </proxy>
              -->
              <!-- 确保下面的路径正确且生效, 此时应优先读取本地的 maven 仓库 不要去配置 mirror-->
          
            </proxies>
          
            <!-- servers
             | This is a list of authentication profiles, keyed by the server-id used within the system.
             | Authentication profiles can be used whenever maven must make a connection to a remote server.
             |-->
            <!-- <servers>
              <server
               | Specifies the authentication information to use when connecting to a particular server,
            identified by
               | a unique name within the system (referred to by the 'id' attribute below).
               |
               | NOTE: You should either specify username/password OR privateKey/passphrase, since these pairings
            are
               |       used together.
               |
              <server>
                <id>deploymentRepo</id>
                <username>repouser</username>
                <password>repopwd</password>
              </server>
              -->
          
            <!-- Another sample, using keys to authenticate.
              <server>
                <id>siteServer</id>
                <privateKey>/path/to/private/key</privateKey>
                <passphrase>optional; leave empty if not used.</passphrase>
              </server>
              
                <server>
                  <id>nexus</id>
                  <username>admin</username>
                  <password>admin8btc</password>
                  <configuration>
                  <timeout>5000</timeout>
                </configuration>
              </server>
            </servers>
          -->
            <!-- mirrors
             | This is a list of mirrors to be used in downloading artifacts from remote repositories.
             |
             | It works like this: a POM may declare a repository to use in resolving certain artifacts.
             | However, this repository may have problems with heavy traffic at times, so people have mirrored
             | it to several places.
             |
             | That repository definition will have a unique id, so we can create a mirror reference for that
             | repository, to be used as an alternate download site. The mirror site will be the preferred
             | server for that repository.
             |-->
            <mirrors>
              <!-- mirror
               | Specifies a repository mirror site to use instead of a given repository. The repository that
               | this mirror serves has an ID that matches the mirrorOf element of this mirror. IDs are used
               | for inheritance and direct lookup purposes, and must be unique across the set of mirrors.
               |
              <mirror>
                <id>mirrorId</id>
                <mirrorOf>repositoryId</mirrorOf>
                <name>Human Readable Name for this Mirror.</name>
                <url>http://my.repository.com/repo/path</url>
              </mirror>
               -->
              <!-- <mirror>
                <id>alimaven</id>
                <name>aliyun maven</name>
                <url>https://maven.aliyun.com/repository/public/</url>
                <mirrorOf>central</mirrorOf>
              </mirror> -->
            </mirrors>
          
            <profiles>
              <profile>
                <id>local-repo</id>
                <repositories>
                  <repository>
                    <id>local-first</id>
                    <url>file://${user.home}/.m2/repository</url>
                    <releases>
                      <enabled>true</enabled>
                    </releases>
                    <snapshots>
                      <enabled>true</enabled>
                    </snapshots>
                  </repository>
                  <repository>
                    <id>central</id>
                    <url>https://repo.maven.apache.org/maven2</url>
                    <releases>
                      <enabled>true</enabled>
                    </releases>
                    <snapshots>
                      <enabled>false</enabled>
                    </snapshots>
                  </repository>
                </repositories>
              </profile>
          
              <profile>
                <pluginRepositories>
                  <pluginRepository>
                    <id>aliyun-public</id>
                    <name>阿里云公共仓库</name>
                    <url>https://maven.aliyun.com/repository/public</url>
                  </pluginRepository>
          
                </pluginRepositories>
              </profile>
          
              <profile>
                <id>staged-releases</id>
                <repositories>
                  <repository>
                    <id>staged-releases</id>
                    <url>https://repository.apache.org/content/groups/staging/</url>
                  </repository>
                </repositories>
                <pluginRepositories>
                  <pluginRepository>
                    <id>staged-releases</id>
                    <url>https://repository.apache.org/content/groups/staging/</url>
                  </pluginRepository>
                </pluginRepositories>
              </profile>
            </profiles>
            <!-- profile
               | Specifies a set of introductions to the build process, to be activated using one or more of the
               | mechanisms described above. For inheritance purposes, and to activate profiles via
            <activatedProfiles/>
               | or the command line, profiles have to have an ID that is unique.
               |
               | An encouraged best practice for profile identification is to use a consistent naming convention
               | for profiles, such as 'env-dev', 'env-test', 'env-production', 'user-jdcasey', 'user-brett', etc.
               | This will make it more intuitive to understand what the set of introduced profiles is attempting
               | to accomplish, particularly when you only have a list of profile id's for debug.
               |
               | This profile example uses the JDK version to trigger activation, and provides a JDK-specific
            repo.
              <profile>
                <id>jdk-1.4</id>
          
                <activation>
                  <jdk>1.4</jdk>
                </activation>
          
                <repositories>
                  <repository>
                    <id>jdk14</id>
                    <name>Repository for JDK 1.4 builds</name>
                    <url>http://www.myhost.com/maven/jdk14</url>
                    <layout>default</layout>
                    <snapshotPolicy>always</snapshotPolicy>
                  </repository>
                </repositories>
              </profile>
              -->
          
            <!--
               | Here is another profile, activated by the system property 'target-env' with a value of 'dev',
               | which provides a specific path to the Tomcat instance. To use this, your plugin configuration
               | might hypothetically look like:
               |
               | ...
               | <plugin>
               |   <groupId>org.myco.myplugins</groupId>
               |   <artifactId>myplugin</artifactId>
               |
               |   <configuration>
               |     <tomcatLocation>${tomcatPath}</tomcatLocation>
               |   </configuration>
               | </plugin>
               | ...
               |
               | NOTE: If you just wanted to inject this configuration whenever someone set 'target-env' to
               |       anything, you could just leave off the <value/> inside the activation-property.
               |
              <profile>
                <id>env-dev</id>
          
                <activation>
                  <property>
                    <name>target-env</name>
                    <value>dev</value>
                  </property>
                </activation>
          
                <properties>
                  <tomcatPath>/path/to/tomcat/instance</tomcatPath>
                </properties>
              </profile>
              -->
          
          
            <!-- activeProfiles
             | List of profiles that are active for all builds.
             |
            <activeProfiles>
              <activeProfile>alwaysActiveProfile</activeProfile>
              <activeProfile>anotherAlwaysActiveProfile</activeProfile>
            </activeProfiles>
            -->
            <!-- <activeProfiles> -->
            <!--make
            the profile active all the time, profile 里要有id-->
            <!-- <activeProfile>8btc-nexus</activeProfile> 
            </activeProfiles> -->
          
            <activeProfiles>
              <activeProfile>local-repo</activeProfile>
              <!--activeProfile>staged-releases</activeProfile-->
            </activeProfiles>
          </settings>
          
          ' > $HOME/.m2/settings.xml

      - name: cat /home/runner/.m2/settings.xml
        run: |
          cat /home/runner/.m2/settings.xml

      - name: Compile
        run: |
          mvn clean compile -U -Dmaven.javadoc.skip=true -ntp

      - name: Install JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'zulu'
      - name: Prepare env and service
        run: |
          $TRAVIS_DIR/install-backend.sh $BACKEND

      - name: Install JDK ${{ matrix.JAVA_VERSION }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.JAVA_VERSION }}
          distribution: 'zulu'

      - name: Run unit test
        run: |
          $TRAVIS_DIR/run-unit-test.sh $BACKEND

      - name: Run core test
        run: |
          $TRAVIS_DIR/run-core-test.sh $BACKEND

      - name: Run api test
        run: |
          $TRAVIS_DIR/run-api-test.sh $BACKEND $REPORT_DIR

      - name: Run raft test
        if: ${{ env.BACKEND == 'rocksdb' }}
        run: |
          $TRAVIS_DIR/run-api-test-for-raft.sh $BACKEND $REPORT_DIR

      - name: Run TinkerPop test
        if: ${{ env.RELEASE_BRANCH == 'true' }}
        run: |
          $TRAVIS_DIR/run-tinkerpop-test.sh $BACKEND tinkerpop

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3.0.0
        with:
          file: ${{ env.REPORT_DIR }}/*.xml
